dmx_poc:
  target: dynamically #"{{env_var('DBT_DB_TARGET')}}"
  outputs:
    dynamically:
      type: oracle
      user: "{{env_var('DBT_ORCL_USER_PROXY')}}"
      pass: "{{env_var('DBT_ORCL_PASS')}}"
      protocol: tcp
      host: "{{env_var('DBT_ORCL_HOST')}}"
      database: "{{env_var('DBT_ORCL_DB')}}"
      port: 1521
      service: "{{env_var('DBT_ORCL_SERVICE')}}"
      schema: "{{env_var('DBT_ORCL_SCHEMA')}}"
      threads: 10
config:
  send_anonymous_usage_stats: False