dmx_poc:
  target: "{{env_var('DBT_DB_TARGET')}}"
  outputs:
    PROD:
      type: oracle
      user: "{{env_var('DBT_ORCL_USER_PROXY')}}"
      pass: "{{env_var('DBT_ORCL_PASS')}}"
      protocol: tcp
      host: dm09-scan.adeo.no
      database: "{{env_var('DBT_ORCL_DB')}}"
      port: 1521
      service: dwh_ha
      schema: "{{env_var('DBT_ORCL_SCHEMA')}}"
      threads: 10
    DEV:
      type: oracle
      user: "{{env_var('DBT_ORCL_USER_PROXY')}}"
      pass: "{{env_var('DBT_ORCL_PASS')}}"
      protocol: "tcp"
      host: dm07-scan.adeo.no
      database: "{{env_var('DBT_ORCL_DB')}}"
      port: 1521
      service: dwhr
      schema: "{{env_var('DBT_ORCL_SCHEMA')}}"
      threads: 10
config:
  send_anonymous_usage_stats: False