dmx_poc:
  target: "{{env_var('DBT_DB_TARGET')}}"
  outputs:
    U:
      type: oracle
      user: "{{env_var('DBT_ENV_SECRET_USER')}}"
      pass: "{{env_var('DBT_ENV_SECRET_PASS')}}"
      protocol: tcp
      host: dm07-scan.adeo.no
      port: 1521
      service: dwhu1
      database: dwhu1
      schema: "{{env_var('DBT_DB_SCHEMA')}}"
      threads: 10
    R:
      type: oracle
      user: "{{env_var('DBT_ENV_SECRET_USER')}}"
      pass: "{{env_var('DBT_ENV_SECRET_PASS')}}"
      protocol: tcp
      host: dm07-scan.adeo.no
      database: dwhr
      port: 1521
      service: dwhr
      schema: "{{env_var('DBT_DB_SCHEMA')}}"
      threads: 10
    Q:
      type: oracle
      user: "{{env_var('DBT_ENV_SECRET_USER')}}"
      pass: "{{env_var('DBT_ENV_SECRET_PASS')}}"
      protocol: tcp
      host: dm07-scan.adeo.no
      database: dwhq0
      port: 1521
      service: dwhq0
      schema: "{{env_var('DBT_DB_SCHEMA')}}"
      threads: 10
    P:
      type: oracle
      user: "{{env_var('DBT_ENV_SECRET_USER')}}"
      pass: "{{env_var('DBT_ENV_SECRET_PASS')}}"
      protocol: tcp
      host: dm09-scan.adeo.no
      database: dwh
      port: 1521
      service: dwh_ha
      schema: "{{env_var('DBT_DB_SCHEMA')}}"
      threads: 10
    PROD:
      type: oracle
      user: "{{env_var('DBT_ORCL_USER_PROXY')}}"
      pass: "{{env_var('DBT_ORCL_PASS')}}"
      protocol: tcp
      host: dm09-scan.adeo.no
      database: dwh
      port: 1521
      service: dwh_ha
      schema: "{{env_var('DBT_ORCL_SCHEMA')}}"
      threads: 10
config:
  send_anonymous_usage_stats: False