ALTER SESSION SET CONTAINER = XEPDB1;
CREATE USER dbt_test IDENTIFIED BY "example";

GRANT CREATE SESSION TO dbt_test;
GRANT CREATE TABLE TO dbt_test;
GRANT CREATE ANY VIEW TO dbt_test;
GRANT UNLIMITED TABLESPACE TO dbt_test;
