ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER dbt_test IDENTIFIED BY "example";
GRANT ALL PRIVILEGES TO dbt_test;
GRANT UNLIMITED TABLESPACE TO dbt_test;

CREATE USER dvh_syfo IDENTIFIED BY "example";
GRANT ALL PRIVILEGES TO dvh_syfo;
GRANT UNLIMITED TABLESPACE TO dvh_syfo;

CREATE USER dvh_syfra IDENTIFIED BY "example";
GRANT ALL PRIVILEGES TO dvh_syfra;
GRANT UNLIMITED TABLESPACE TO dvh_syfra;
