version: 2

sources:
  - name: dmx_pox_dialogmote
    tags: ['syfo']
    description: 'Dialogmøte data som kommer fra MODIA '
    schema: DVH_SYFO
    tables:
      - name: ARBEIDS_PERIODE_SMALL
        description: Arbeidsperiode med unike nøklerg
      - name: raw_isdialogmote
        description: dialogmote data - raw
      - name: fk_syfo_person_oversikt_status
        description: Kandidater for dialogmøte med korrekte nav -enheter
 # - name: dmx_pox_oppfolging
   # tags: ['syfo']
   # description: 'Oppfølging samt diverse felles dimensjoner'
   # schema: DT_P
   # tables:
   #   - name: DIM_TID
   #     description: Tidsdimensjonen
   #   - name: DIM_ORGANISASJON
   #     description: Organiasjonene - alle
   #   - name: DIM_VARIGHET
   #     description: Varighet - alle
   #   - name: DIM_NAERING
   #     description: Næringer
   #   - name: FAK_SF_HENDELSE_DAG
   #     description: Arena fakta per dag
   #   - name: DIM_GEOGRAFI
   #     description: Geografi
   #   - name: DIM_DIAGNOSE
   #     description: 'Diagnoser hovedkategori'
  - name: dmx_poc_person
    tags: ['syfo']
    description: 'henter fra DT_PERSON'
    schema: DT_PERSON
    tables:
      - name: DIM_PERSON1
        description: informasjon om person
  - name: dmx_poc_sykefravar
    tags: ['syfo']
    description: 'henter fra diverse sykefraværsfakta'
    schema: DVH_SYKM
    tables:
      - name: FAK_SYKM_SYKEFRAVAR_TILFELLE
        description: 'Sykefraværstilfeller'
  - name: dmx_pov_sykefravar_andre
    tags: ['syfo']
    description: 'henter fra andre tabeller'
    schema: DK_P
    tables:
      - name: ARBEIDSPERIODE
        description: 'Oversikt over hvor personen jobbet'