version: 2

sources:
  - name: dvh_sykm
    tags: ['sykm']
    schema: dvh_sykm
    tables:
      - name: sykm_sykmelding
        description: >
          Meldinger på Kafka-konsument fra topic teamsykmelding.ok-sykmelding og teamsykmelding.manuell-behandling-sykmelding.
          Tidligere privat-syfo-sm2013-automatiskBehandling og privat-syfo-sm2013-manuellBehandling (t.o.m. 09.03.2022).
        freshness:
          warn_after: {count: 1, period: hour}
        loaded_at_field: "CAST(lastet_dato AS TIMESTAMP)"
