version: 2

sources:
  - name: dmx_pox_dialogmote
    description: 'Dialogdata '
    database: dwhu1
    schema: DVH_SYFO
    tables:
      - name: FK_ISDIALOGMOTE_DM2
  - name: dmx_pox_oppfolging
    description: 'Oppfølging'
    database: dwhu1
    schema: DT_P
    tables:
      - name: FAK_SF_OPPFOLGING_D2_MND