version: 2

sources:
  - name: dmx_pox_dialogmote
    description: 'Dialogmøte data som kommer fra MODIA '
    schema: DVH_SYFO
    tables:
      - name: FK_ISDIALOGMOTE_DM2
        description: Informasjon om dialogmøte som kommer fra modia
  - name: dmx_pox_oppfolging
    description: 'Oppfølging samt diverse felles dimensjoner'
    schema: DT_P
    tables:
      - name: FAK_SF_OPPFOLGING_D2_MND
        description: Facta med oppfølgingsdata
      - name: DIM_TID
        description: Tidsdimensjonen
      - name: DIM_ORG
        description: Organiasjonene - alle
      - name: DIM_VARIGHET 
        description: Varighet - alle
      - name: DIM_NAERING 
        description: Næringer 
  - name: dmx_poc_person
    description: 'henter fra DT_PERSON'
    schema: DT_PERSON
    tables:
      - name: DIM_PERSON1
        description: informasjon om person