---
version: "3.1"
services:
  db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    restart: always
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/startup
    environment:
      ORACLE_PWD: example
    ports:
      - "1521:1521"
      - "5500:5500"
