dmx_poc:
  target: dev
  outputs:
    dev:
      type: oracle
      host: "{{env_var('DBT_ORCL_HOST_U')}}"
      user: "{{env_var('DBT_ORCL_USER_U')}}"
      password: "{{env_var('DBT_ORCL_PASS_U')}}"
      dbname: "{{env_var('DBT_ORCL_DB_U')}}"
      port: 1521
      service: "{{env_var('DBT_ORCL_SERVICE_U')}}"
      schema: dvh_syfo
      threads: 4        