dmx_poc:
  target: "{{env_var('DBT_DEV')}}"
  outputs:
    dev:
      type: oracle
      host: "{{env_var('DBT_ORCL_HOST_U')}}"
      user: "{{env_var('DBT_ORCL_USER_U')}}"
      password: "{{env_var('DBT_ORCL_PASS_U')}}"
      dbname: "{{env_var('DBT_ORCL_DB_U')}}"
      port: 1521
      service: "{{env_var('DBT_ORCL_SERVICE_U')}}"
      schema: "{{env_var('DBT_ORCL_SCHEMA')}}"
      threads: 4
    prod:
      type: oracle
      host: "{{env_var('DBT_ORCL_HOST_PROD')}}"
      user: "{{env_var('DBT_ORCL_USER_PROD_PROXY')}}"
      password: "{{env_var('DBT_ORCL_PASS_PROD')}}"
      dbname: "{{env_var('DBT_ORCL_DB_PROD')}}"
      port: 1521
      service: "{{env_var('DBT_ORCL_SERVICE_PROD')}}"
      schema: "{{env_var('DBT_ORCL_SCHEMA')}}"
      threads: 4