version: 2

sources:
  - name: dt_person
    schema: dt_person
    tables:
      - name: dvh_person_ident_off_id
  - name: dvh_syfra
    schema: dvh_syfra
    tables:
      - name: ssb_syfra_teller_kv
